In [ ]:
numpy


In [1]:
# 1. array module

from array import array
my_array=array('i',[1,2,3,4])      # 'i'  indicates integer data type

In [2]:
my_array

array('i', [1, 2, 3, 4])

In [3]:
import numpy as np
my_array=np.array([1,2,3,4,5,6])


In [4]:
my_array+3

array([4, 5, 6, 7, 8, 9])

In [5]:
type(my_array)

numpy.ndarray

In [ ]:
import numpy as np
my_number=np.array([1,2,3,4,5])

In [6]:
import numpy as np
my_numpy_array=np.array([1,2,3,4,5])
new_arr=my_numpy_array*3
new_arr

array([ 3,  6,  9, 12, 15])

In [7]:
type(my_numpy_array)

numpy.ndarray

In [8]:
my_arr=np.array([1,2,3])
res=my_arr*2
res

array([2, 4, 6])

In [9]:
print(res)

[2 4 6]


In [10]:
my_arr

array([1, 2, 3])

In [12]:
my_arr>2

array([False, False,  True])

In [13]:
import seaborn as sns

In [15]:
df=sns.load_dataset("titanic")


In [16]:
import numpy as np
arr_2d=np.array([[0,1,2,3],[4,5,6,7]])

In [17]:

arr_2d

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [21]:
arr_3d=np.array([[0,1,2,3],[4,5,6,7],[8,9,0,5]])
arr_3d

array([[0, 1, 2, 3],
       [4, 5, 6, 7],
       [8, 9, 0, 5]])

In [18]:
arr_2d+2

array([[2, 3, 4, 5],
       [6, 7, 8, 9]])

In [19]:
arr_2d*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]])

In [22]:
arr_3d-1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8, -1,  4]])

In [23]:
arr_3d-1

array([[-1,  0,  1,  2],
       [ 3,  4,  5,  6],
       [ 7,  8, -1,  4]])

In [ ]:
import pandas as pd
data=pd.read_csv('tit.csv')

In [28]:
print(data.head())

NameError: name 'data' is not defined