In [1]:
# 2. using functions to geneate data
import numpy as np
a33=np.ones((3,4))
type(a33)

numpy.ndarray

In [2]:
a33

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [3]:
a44=np.zeros((2,4))
a44

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
arr1=np.array([1,2,3])

In [5]:
arr1

array([1, 2, 3])

In [6]:
identity_mat=np.eye(3)
identity_mat

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
random_array=np.random.rand(4,4)

In [8]:
random_array

array([[0.87131943, 0.73538353, 0.668427  , 0.69333847],
       [0.18397041, 0.11145148, 0.43938304, 0.10714878],
       [0.67656755, 0.92169878, 0.13713448, 0.38856499],
       [0.62997811, 0.63818636, 0.03450941, 0.54974226]])

In [9]:
random_array

array([[0.87131943, 0.73538353, 0.668427  , 0.69333847],
       [0.18397041, 0.11145148, 0.43938304, 0.10714878],
       [0.67656755, 0.92169878, 0.13713448, 0.38856499],
       [0.62997811, 0.63818636, 0.03450941, 0.54974226]])

In [10]:
# 3. specific dara type

l=[1,2,3,4]

np.array(l,dtype=np.int32)

array([1, 2, 3, 4])

In [11]:
float_array=np.array([1,2,3], dtype=np.float64)
int_array=np.array([1,2,3,4], dtype=np.int32)

In [12]:
float_array

array([1., 2., 3.])

In [13]:
int_array

array([1, 2, 3, 4])

In [14]:
# 4. using array and linespace
# arange()

a44=np.arange(0,12)
a44

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
a66=np.arange(5,7)
a66

array([5, 6])

In [16]:
#  linespace

linespace_array=np.linspace(0,10,6)
linespace_array

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [17]:
linespace_array=np.linspace(1,20,5)
linespace_array

array([ 1.  ,  5.75, 10.5 , 15.25, 20.  ])

In [ ]:
random_array=np.random.rand(4,4)  # CREATES random values in(0,1)
random_array

In [ ]:
Numpy array Indexing

In [18]:
# 1. basic indexing

arr=np.array([10,20,30,40])
print(arr[0])

10


In [19]:
arr[-1]

40

In [20]:
# 2d example
matrix=np.array([[1,2,3],
                 [4,5,6]])
matrix[0,1]

2

In [21]:
print(matrix[1,2])

6


In [22]:
# 2. slicing
# 1d array slicing

arr=np.array([10,20,30,40,50,60])
print(arr[0:4])

[10 20 30 40]


In [23]:
print(arr[1:])

[20 30 40 50 60]


In [24]:
print(arr[:-1])

[10 20 30 40 50]


In [25]:
print(arr[::-1])

[60 50 40 30 20 10]


In [26]:
print(arr[::2])

[10 30 50]


In [27]:
print(arr[0:4:3])

[10 40]


In [28]:
print(arr[:3])

[10 20 30]


In [29]:
# 2d array slicing

matrix=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matrix[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [30]:
print(matrix[1:3,1:3])

[[5 6]
 [8 9]]


In [31]:
# 8
print(matrix[2:3,1:2])

[[8]]


In [32]:
print(matrix[2:,1:])

[[8 9]]


In [33]:
matrix[2:3,1:2]

array([[8]])

In [34]:
#  numpy array copy vs view

#  view

a=np.array([1,2,3,4])
b=a[1:3]  # view
b

array([2, 3])

In [35]:
b[0]=99
print(a)

[ 1 99  3  4]


In [36]:
a=[1,2,3,4]
b=a
b

[1, 2, 3, 4]

In [37]:
b[2]=99
b

[1, 2, 99, 4]

In [38]:
a

[1, 2, 99, 4]

In [39]:
# copy
a=np.array([1,2,3,4])
b=a[1:3].copy()  # view
b[0]=99
print(a)
print(b)

[1 2 3 4]
[99  3]


In [40]:
#  numpy shape and reshaping
#  shape
arr=np.array([[1,2,3],[4,5,6]])
print(arr.shape)

(2, 3)


In [41]:
arr=np.array([0,1,2,3,4,5,6,7,8,9,10,11])

In [42]:
a=np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])