In [1]:
import numpy as np


In [2]:
uniform=np.random.rand(3,3)
print("Uniform distribution:\n",uniform)


Uniform distribution:
 [[0.27143517 0.71636165 0.0495914 ]
 [0.6307153  0.4404003  0.96912219]
 [0.0528298  0.91636363 0.81982539]]


In [ ]:
                                              searching in arrays

In [3]:
arr=np.array([1,2,3,4,5])
np.where(arr>3)

(array([3, 4], dtype=int64),)

In [4]:
print("where >3:",np.where(arr>3))

where >3: (array([3, 4], dtype=int64),)


In [6]:
np.where(arr<=2)

(array([0, 1], dtype=int64),)

In [7]:
np.argmax([1,2,3,4,5])

4

In [8]:
np.argmax(arr)

4

In [9]:
np.argmax(arr)

4

In [10]:
#  seraches sorted

sorted_arr=np.array([1,2,3,4,7])
np.searchsorted(sorted_arr,6)

4

In [11]:
np.searchsorted(sorted_arr,100)

5

In [12]:
#  extract
arr=np.array([1,2,3,4,5])
np.extract(arr>3,arr)

array([4, 5])

In [13]:
8# transpose
arr=np.array([[1,2,3,4],
             [5,6,7,8]])
np.transpose(arr)

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [14]:
#  mean calculation

arr=np.array([1,2,3,4,5])
print("mean value:",np.mean(arr))

mean value: 3.0


In [ ]:
splitting arrays
np.split()

In [16]:
arr=np.array([1,2,3,4,5,6,7,8])
np.split(arr,4)   # splitting parts equally

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]

In [17]:
# splitting at exact position
arr=np.array([1,2,3,4,5,6])
np.split(arr,[1,4])

[array([1]), array([2, 3, 4]), array([5, 6])]

In [18]:
np.split(arr,[1,3,5])

[array([1]), array([2, 3]), array([4, 5]), array([6])]

In [19]:
# splitting matrix

matrix=np.array([[1,2,3,4],
             [5,6,7,8]])
np.split(matrix ,4,axis=1)

[array([[1],
        [5]]),
 array([[2],
        [6]]),
 array([[3],
        [7]]),
 array([[4],
        [8]])]

In [20]:
matrix=np.array([[1,2,3],
             [4,5,6]])
np.split(matrix ,3,axis=1)     # split columns

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

In [21]:
# split rows

np.split(matrix ,2,axis=0) 

[array([[1, 2, 3]]), array([[4, 5, 6]])]

In [22]:
# sorting arrays

arr=np.array([1,2,3,4,5,6])
print("sorted array:",np.sort(arr))

sorted array: [1 2 3 4 5 6]


In [23]:
arr.sort()
print("in place sorted:",arr)

in place sorted: [1 2 3 4 5 6]


In [24]:
matrix=np.array([[3,2,1],
             [6,4,5]])
print("sorted rows:\n",np.sort(matrix,axis=1))

sorted rows:
 [[1 2 3]
 [4 5 6]]
